name: Maven Central Deployment

on:
  # Allows manual runs from the Actions tab for testing
  workflow_dispatch:

  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z0-9]+)?'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java and Maven Settings
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: ossrh

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --passphrase ${{ secrets.GPG_PASSPHRASE }} --import private.key

      - name: Deploy to Maven Central
        run: |
          # The mvn command relies on the GPG key being imported in the previous step
          mvn clean deploy -B \
            -DskipTests=true \
            -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}